import json

def create_question(q_id, q_num, topic, subtopic, diff, text, options, ans_idx, exp="", type_="single"):
    return {
        "id": q_id,
        "displayNumber": str(q_num),
        "type": type_,
        "metadata": {
            "topic": topic,
            "subtopic": subtopic,
            "difficulty": diff,
            "questionType": "Single Correct MCQ" if type_ == "single" else "Other"
        },
        "text": text,
        "options": [{"id": str(i+1), "text": opt} for i, opt in enumerate(options)],
        "answer": str(ans_idx),
        "explanation": exp
    }

questions_q = [
    create_question("q-quant-1", 1, "Linear Equations", "Intersection of lines", "medium", 
        "The intersection point of the lines 3x - 2y = 12 and 5x + y = 33 lies on which of the following lines?", 
        ["2x + 3y = 21", "4x - y = 20", "x + 4y = 16", "3x - 4y = 8"], 1),
    create_question("q-quant-2", 2, "Mensuration", "Triangles and Circles", "hard", 
        "A circular track passes through all three vertices of a triangular field with side lengths 52 m, 56 m, and 60 m. What is the radius of the circular track?", 
        ["31.5 m", "32.5 m", "33.5 m", "34.5 m"], 2),
    create_question("q-quant-3", 3, "Profit & Loss", "Marked Price", "medium", 
        "By selling an article at 75% of its marked price, a trader makes a loss of 10%. If he sells it at 90% of its marked price, what will be his profit or loss percentage?", 
        ["8% profit", "10% profit", "8% loss", "10% loss"], 1),
    create_question("q-quant-4", 4, "Percentage", "Income & Expenditure", "medium", 
        "Ravi spends 60% of his monthly income on household items and 25% of the remaining on transport. If his income is increased by 20% and his household expenditure is increased by 10%, but his transport expenditure remains the same, what is the percentage change in his savings?", 
        ["46.67% increase", "43.33% increase", "46.67% decrease", "43.33% decrease"], 1),
    create_question("q-quant-5", 5, "Time & Work", "Efficiency Chains", "hard", 
        "A and B together can do a piece of work in 12 days. B's efficiency is 25% less than C's efficiency. A, B, and C together can do the same work in 8 days. In how many days can A alone complete 2/3 of the work?", 
        ["12.8 days", "15.2 days", "14.4 days", "10.6 days"], 1),
    create_question("q-quant-6", 6, "Number System", "GCD and Remainders", "medium", 
        "Let x be the greatest number which when divides 415, 627, and 945 leaves the same remainder in each case. What is the sum of the digits of x?", 
        ["7", "8", "9", "10"], 1),
    create_question("q-quant-7", 7, "Simple Interest", "Amounts over time", "easy", 
        "A sum of money invested at simple interest amounts to Rs. 8,400 in 3 years and to Rs. 9,600 in 5 years. What is the principal sum?", 
        ["Rs. 6000", "Rs. 6600", "Rs. 7000", "Rs. 7200"], 2),
    create_question("q-quant-8", 8, "Ages", "Ratios over time", "medium", 
        "Five years ago, the ratio of the ages of A and B was 4:5. Eight years from now, the ratio of their ages will be 17:20. What is the ratio of A's present age to B's age 4 years ago?", 
        ["19:22", "17:21", "20:23", "19:24"], 1),
    create_question("q-quant-9", 9, "Simplification", "Fractions and BODMAS", "medium", 
        "Evaluate: 3 1/4 ÷ [ 2 1/2 of ( 4 1/3 - 1 5/6 ) ] + 3/5", 
        ["1 3/25", "1 1/25", "2 3/25", "28/15"], 1),
    create_question("q-quant-10", 10, "Percentage", "Weighted average", "medium", 
        "The price of a laptop is 120% more than the price of a tablet. If the price of the laptop is increased by 15% and the price of the tablet is decreased by 10%, what is the percentage increase in the total cost of buying 2 laptops and 3 tablets?", 
        ["180/37 %", "190/37 %", "160/37 %", "175/37 %"], 1),
    create_question("q-quant-11", 11, "Pipes & Cisterns", "Alternative workings", "hard", 
        "Pipe A can fill a tank in 18 hours and Pipe B in 24 hours. Pipe C can empty the full tank in 36 hours. If all three pipes are opened together for 4 hours, and then Pipe A is closed, how many more hours will it take to fill the remaining tank?", 
        ["52 hours", "48 hours", "54 hours", "56 hours"], 1),
    create_question("q-quant-12", 12, "Mensuration", "Volume and Flow Rates", "hard", 
        "A bucket is in the shape of a frustum of a cone with radii of its circular ends being 28 cm and 21 cm, and its depth is 30 cm. Water flows into the bucket through a cylindrical pipe of radius 1.4 cm at a speed of 50 cm/sec. How many seconds will it take to fill the empty bucket completely? (Take pi = 22/7)", 
        ["185 seconds", "175 seconds", "195 seconds", "205 seconds"], 1),
    create_question("q-quant-13", 13, "Profit & Loss", "Discounts", "medium", 
        "A retailer marks up his goods by 40% above the cost price and allows a discount of 15%. If he earns a profit of Rs. 475, what is the marked price of the goods?", 
        ["Rs. 3500", "Rs. 2500", "Rs. 4200", "Rs. 3800"], 1),
    create_question("q-quant-14", 14, "Partnership", "Changing Capital", "medium", 
        "A, B, and C started a business with initial investments in the ratio 3:4:5. After 4 months, A doubled his investment, and after another 4 months, B halved his investment. If the total annual profit is Rs. 14,800, what is C's share?", 
        ["Rs. 5550", "Rs. 5450", "Rs. 4850", "Rs. 3700"], 1),
    create_question("q-quant-15", 15, "Boats & Streams", "Ratio of times", "medium", 
        "The time taken by a boat to travel a certain distance upstream is 7/4 times the time taken to travel the same distance downstream. If the speed of the current is 3 km/hr, what is the speed of the boat in still water?", 
        ["11 km/hr", "12 km/hr", "10 km/hr", "14 km/hr"], 1),
    create_question("q-quant-16", 16, "Mixtures & Alligations", "Ratios", "medium", 
        "Alloy A contains copper and zinc in the ratio 5:3. Alloy B contains copper and zinc in the ratio 3:4. In what ratio should Alloys A and B be mixed to get a new alloy containing equal amounts of copper and zinc?", 
        ["4:7", "5:8", "3:5", "7:9"], 1)
]

questions_verbal = [
    create_question("q-verb-17", 17, "Vocabulary", "Idioms", "hard", 
        "Select the most appropriate meaning of the given idiom:\n\"To tilt at windmills\"", 
        ["To attack imaginary enemies", "To build innovative structures", "To waste time on trivial matters", "To challenge the authority directly"], 1),
    create_question("q-verb-18", 18, "Grammar", "Sentence Improvement", "medium", 
        "Select the option that will improve the underlined part of the sentence.\nNo sooner had she finished the speech [then the audience gave] a standing ovation.", 
        ["than the audience gave", "when the audience gave", "then the audience given", "No improvement"], 1),
    create_question("q-verb-19", 19, "Vocabulary", "One word substitution", "medium", 
        "Select the word which means the same as the group of words given.\nA person who collects or has a great love of books", 
        ["Bibliophile", "Philatelist", "Numismatist", "Lexicographer"], 1),
    create_question("q-verb-20", 20, "Para Jumbles", "Sentence Rearrangement", "hard", 
        "Rearrange the parts of the sentence in correct order.\nA. The phenomenon of quantum entanglement\nB. states that two particles can be intimately linked\nC. to understand the fundamental nature of the universe\nD. independent of the distance separating them", 
        ["ABDC", "ADBC", "BADC", "CABD"], 1),
    create_question("q-verb-21", 21, "Vocabulary", "Synonyms", "medium", 
        "Select the most appropriate synonym of the bracketed word to fill in the blank.\nThe committee's (ephemeral) popularity was largely due to the crisis at hand.", 
        ["Transient", "Enduring", "Profound", "Superficial"], 1),
    create_question("q-verb-22", 22, "Vocabulary", "Spelling", "easy", 
        "Select the correctly spelt word.", 
        ["Accommodate", "Acommodate", "Accomodate", "Accomadate"], 1),
    create_question("q-verb-23", 23, "Grammar", "Sentence Improvement", "medium", 
        "Select the option that will improve the underlined part of the sentence.\nHe warned the workers that [unless they do not complete] the project on time, they will be fired.", 
        ["unless they complete", "until they do not complete", "lest they complete", "No improvement"], 1),
    create_question("q-verb-24", 24, "Vocabulary", "Idioms", "medium", 
        "Select the most appropriate meaning of the given idiom:\n\"To bite the bullet\"", 
        ["To force yourself to do something unpleasant", "To get injured in a conflict", "To make a tough decision blindly", "To speak aggressively"], 1),
    create_question("q-verb-25", 25, "Vocabulary", "Antonyms", "medium", 
        "Select the most appropriate antonym of the bracketed word to fill in the blank.\nDespite the (cacophony) in the market, she managed to focus on her reading.", 
        ["Harmony", "Tumult", "Discord", "Clatter"], 1),
    create_question("q-verb-26", 26, "Para Jumbles", "Sentence Rearrangement", "medium", 
        "Given below are four jumbled sentences. Select the option that gives their correct order.\nA. However, this is changing rapidly as renewable energy becomes cheaper.\nB. For decades, coal has been the dominant source of electricity generation.\nC. Solar and wind power are leading this global transition.\nD. Consequently, many countries are phasing out coal power plants entirely.", 
        ["BADC", "BACD", "BCAD", "ABCD"], 2),
    create_question("q-verb-27", 27, "Vocabulary", "Spelling", "medium", 
        "Select the INCORRECTLY spelt word.", 
        ["Millennium", "Fascinate", "Maintainance", "Irresistible"], 3),
    create_question("q-verb-28", 28, "Vocabulary", "One word substitution", "hard", 
        "Select the word which means the same as the group of words given.\nA person who is indifferent to both pleasure and pain", 
        ["Stoic", "Ascetic", "Epicurean", "Misanthrope"], 1),
    create_question("q-verb-29", 29, "Vocabulary", "Idioms", "medium", 
        "Select the most appropriate meaning of the given idiom:\n\"Cut to the chase\"", 
        ["To get to the main point", "To edit a movie", "To lose an opportunity", "To interrupt someone"], 1),
    create_question("q-verb-30", 30, "Reading Comprehension", "RC - Fact", "medium", 
        "Read the passage and answer the question:\nThe transition to a circular economy represents a fundamental shift in how we produce and consume goods. Unlike the traditional linear model—take, make, dispose—a circular economy aims to design out waste, keep materials in use, and regenerate natural systems. This approach not only mitigates environmental degradation but also offers substantial economic benefits by reducing supply chain risks and fostering innovation in product design.\n\nAccording to the passage, what is a primary goal of the circular economy?", 
        ["To design out waste and keep materials in use", "To increase the consumption of disposable goods", "To traditionalize the linear economic model", "To eliminate the need for product innovation"], 1),
    create_question("q-verb-31", 31, "Reading Comprehension", "RC - Theme", "medium", 
        "Read the passage in the previous question and answer:\nWhat is the central theme of the passage?", 
        ["The shift towards sustainable and regenerative economic practices", "The inevitable decline of global supply chains", "The environmental dangers of technological innovation", "The historical evolution of linear economies"], 1),
    create_question("q-verb-32", 32, "Reading Comprehension", "RC - Vocab", "medium", 
        "Read the passage in the previous questions and answer:\nWhich of the following is closest in meaning to the word 'mitigates' as used in the passage?", 
        ["Alleviates", "Aggravates", "Initiates", "Complicates"], 1)
]

questions_reasoning = [
    create_question("q-reas-33", 33, "Non-Verbal", "Figure Series", "medium", 
        "Select the figure that will come next in the following figure series.\n\n[Figure Placeholder: A series of geometric shapes rotating 90 degrees clockwise with an alternating shaded quadrant]", 
        ["[Figure 1]", "[Figure 2]", "[Figure 3]", "[Figure 4]"], 1),
    create_question("q-reas-34", 34, "Non-Verbal", "Mirror Image", "easy", 
        "Select the correct mirror image of the given combination when the mirror is placed at MN as shown.\n\n[Figure Placeholder: Alphanumeric string 'KL97Q']", 
        ["[Figure 1]", "[Figure 2]", "[Figure 3]", "[Figure 4]"], 1),
    create_question("q-reas-35", 35, "Non-Verbal", "Dice", "medium", 
        "Two different positions of the same dice are shown, the six faces of which are numbered from 1 to 6. Select the number that will be on the face opposite to the face having the number '5'.\n\n[Figure Placeholder: Dice positions showing (1, 4, 5) and (1, 2, 6)]", 
        ["3", "2", "6", "4"], 2),
    create_question("q-reas-36", 36, "Non-Verbal", "Figure Completion", "medium", 
        "Select the option figure that will complete the pattern in the given figure.\n\n[Figure Placeholder: A grid with a missing corner containing intersecting diagonals]", 
        ["[Figure 1]", "[Figure 2]", "[Figure 3]", "[Figure 4]"], 1),
    create_question("q-reas-37", 37, "Coding-Decoding", "Letter Shift", "medium", 
        "In a certain code language, 'ROBUST' is written as 'QNATRS'. How will 'ZEBRA' be written in that language?", 
        ["YDAQZ", "YDAQB", "YDAPZ", "YEAQZ"], 1),
    create_question("q-reas-38", 38, "Coding-Decoding", "Number Coding", "hard", 
        "In a certain code language, 'PAINT' is coded as '60', and 'DROP' is coded as '53'. How will 'MARK' be coded in that language?", 
        ["43", "45", "41", "47"], 1),
    create_question("q-reas-39", 39, "Number Series", "Difference Pattern", "medium", 
        "Select the number from among the given options that can replace the question mark (?) in the following series.\n14, 21, 35, 56, 84, ?", 
        ["119", "121", "112", "126"], 1),
    create_question("q-reas-40", 40, "Number Series", "Multiplication Pattern", "hard", 
        "Select the number that can replace the question mark (?) in the following series.\n5, 11, 25, 55, 117, ?", 
        ["243", "245", "239", "251"], 1),
    create_question("q-reas-41", 41, "Seating Arrangement", "Linear", "hard", 
        "Seven people A, B, C, D, E, F, and G are sitting in a straight line facing north. B sits third to the left of G. G sits at one of the extreme ends. A sits second to the right of C. C is not an immediate neighbour of B. E and F are immediate neighbours. E is not sitting at any extreme end. Who sits at the extreme left end?", 
        ["C", "D", "E", "F"], 1),
    create_question("q-reas-42", 42, "Seating Arrangement", "Circular", "medium", 
        "Six friends P, Q, R, S, T, and U are sitting around a circular table facing the centre. P sits second to the right of U. Q sits immediate left of R. S is not an immediate neighbour of P. Who sits opposite to T?", 
        ["U", "Q", "P", "R"], 1),
    create_question("q-reas-43", 43, "Blood Relations", "Verbal", "medium", 
        "Pointing to a photograph, a man says, \"She is the only daughter of my wife's mother-in-law.\" How is the woman in the photograph related to the man?", 
        ["Sister", "Wife", "Mother", "Daughter"], 1),
    create_question("q-reas-44", 44, "Blood Relations", "Coded", "hard", 
        "If A + B means A is the brother of B; A - B means A is the sister of B; A * B means A is the father of B; A / B means A is the mother of B.\nWhich of the following expressions shows that P is the paternal aunt of R?", 
        ["P - Q * R", "P + Q * R", "P - Q / R", "P * Q - R"], 1),
    create_question("q-reas-45", 45, "Syllogism", "Statements", "medium", 
        "Statements:\n1. All cars are buses.\n2. Some buses are trucks.\n3. No truck is a bicycle.\nConclusions:\nI. Some cars are trucks.\nII. No bus is a bicycle.\nIII. Some buses are cars.", 
        ["Only conclusion III follows", "Only I and III follow", "Only II and III follow", "All conclusions follow"], 1),
    create_question("q-reas-46", 46, "Ordering", "Inequalities", "medium", 
        "Among five friends J, K, L, M, and N, each has a different height. J is taller than only L. K is taller than M but shorter than N. Who is the third tallest?", 
        ["M", "K", "N", "J"], 1),
    create_question("q-reas-47", 47, "Analogy", "Letter Clusters", "medium", 
        "Select the option that is related to the third letter-cluster in the same way as the second letter-cluster is related to the first.\nGATE : HCYI :: SINK : ?", 
        ["TKQO", "TKRO", "TLQO", "TKQP"], 1),
    create_question("q-reas-48", 48, "Odd One Out", "Letter Pairs", "medium", 
        "Four letter-clusters have been given, out of which three are alike in some manner and one is different. Select the odd letter-cluster.", 
        ["FHK", "NPS", "SUX", "CFI"], 4),
    create_question("q-reas-49", 49, "Letter Series", "Repeating Block", "medium", 
        "Select the combination of letters that when sequentially placed in the blanks of the given series will complete the series.\na _ c d _ b _ d a b c _", 
        ["b a c d", "b c a d", "b c c d", "c b a d"], 1),
    create_question("q-reas-50", 50, "Alphanumeric Series", "String Ops", "medium", 
        "If all the vowels are dropped from the string 'ALPHANUMERIC', which letter will be the fourth from the right end?", 
        ["M", "N", "R", "H"], 2),
    create_question("q-reas-51", 51, "Mathematical Signs", "Interchange", "medium", 
        "Which two numbers should be interchanged to make the given equation correct?\n14 + 5 × 4 - 12 ÷ 3 = 26", 
        ["4 and 3", "14 and 12", "5 and 3", "12 and 3"], 1),
    create_question("q-reas-52", 52, "Approximation", "BODMAS", "medium", 
        "What approximate value will come in place of the question mark (?) in the following equation?\n24.98 × 15.02 - 110.11 + 39.99 = ?", 
        ["305", "320", "295", "315"], 1),
    create_question("q-reas-53", 53, "Direction Sense", "Angles", "medium", 
        "A man is facing West. He turns 45 degrees in the clockwise direction and then another 180 degrees in the same direction, and then 270 degrees in the anti-clockwise direction. Which direction is he facing now?", 
        ["South-West", "North-West", "South-East", "North-East"], 1),
    create_question("q-reas-54", 54, "Puzzle", "Scheduling", "hard", 
        "Seven lectures are scheduled on seven different days of the same week starting from Monday to Sunday. Lecture P is on Thursday. Two lectures are between P and Q. R is scheduled immediately before Q. Three lectures are between R and S. On which day is S scheduled?", 
        ["Monday", "Tuesday", "Friday", "Saturday"], 2)
]

questions_ga = [
    create_question("q-ga-55", 55, "History", "Modern India", "medium", 
        "Who among the following was the founder of the 'Servants of India Society' in 1905?", 
        ["Gopal Krishna Gokhale", "Bal Gangadhar Tilak", "Lala Lajpat Rai", "Annie Besant"], 1),
    create_question("q-ga-56", 56, "History", "Medieval India", "hard", 
        "The system of Dagh (branding of horses) and Chehra (descriptive roll of soldiers) was introduced by which Delhi Sultan?", 
        ["Alauddin Khalji", "Muhammad bin Tughlaq", "Iltutmish", "Balban"], 1),
    create_question("q-ga-57", 57, "Economy", "Current Affairs", "medium", 
        "Which institution replaced the Planning Commission of India in 2015?", 
        ["NITI Aayog", "Finance Commission", "National Development Council", "Economic Advisory Council"], 1),
    create_question("q-ga-58", 58, "Geography", "Rivers", "medium", 
        "The Majuli island, which is the largest river island in the world, is located on which river?", 
        ["Brahmaputra", "Ganga", "Godavari", "Indus"], 1),
    create_question("q-ga-59", 59, "Sports", "Awards", "medium", 
        "The Major Dhyan Chand Khel Ratna Award, India's highest sporting honour, was formerly known as:", 
        ["Rajiv Gandhi Khel Ratna Award", "Arjuna Award", "Dronacharya Award", "National Sports Award"], 1),
    create_question("q-ga-60", 60, "Culture", "Festivals", "hard", 
        "The famous 'Hornbill Festival' is celebrated in which state of India?", 
        ["Nagaland", "Manipur", "Mizoram", "Assam"], 1),
    create_question("q-ga-61", 61, "Constitution", "Fundamental Rights", "hard", 
        "Which Article of the Indian Constitution guarantees the right to constitutional remedies?", 
        ["Article 32", "Article 21", "Article 226", "Article 14"], 1),
    create_question("q-ga-62", 62, "Science", "Space", "medium", 
        "Which of the following was India's first dedicated multi-wavelength space observatory?", 
        ["AstroSat", "Chandrayaan-1", "Mangalyaan", "Cartosat"], 1),
    create_question("q-ga-63", 63, "Books", "Authors", "medium", 
        "Who is the author of the book 'The Discovery of India'?", 
        ["Jawaharlal Nehru", "Mahatma Gandhi", "Sardar Patel", "Rabindranath Tagore"], 1),
    create_question("q-ga-64", 64, "Geography", "Neighbouring Countries", "easy", 
        "Which of the following Indian states does NOT share a border with Bangladesh?", 
        ["Manipur", "Meghalaya", "Tripura", "Assam"], 1),
    create_question("q-ga-65", 65, "Current Affairs", "Indices", "hard", 
        "In the Global Hunger Index 2023, India was ranked at which position out of 125 countries?", 
        ["111", "107", "101", "94"], 1),
    create_question("q-ga-66", 66, "History", "Ancient India", "medium", 
        "The Harappan site of Dholavira is located in which Indian state?", 
        ["Gujarat", "Rajasthan", "Haryana", "Punjab"], 1),
    create_question("q-ga-67", 67, "Economy", "Banking", "medium", 
        "Which of the following is the central bank of India?", 
        ["Reserve Bank of India", "State Bank of India", "Central Bank of India", "Punjab National Bank"], 1),
    create_question("q-ga-68", 68, "Science", "Biology", "medium", 
        "Which vitamin is also known as Ascorbic Acid?", 
        ["Vitamin C", "Vitamin A", "Vitamin D", "Vitamin B12"], 1),
    create_question("q-ga-69", 69, "Culture", "Classical Dances", "medium", 
        "Kuchipudi is a classical dance form of which Indian state?", 
        ["Andhra Pradesh", "Kerala", "Tamil Nadu", "Odisha"], 1),
    create_question("q-ga-70", 70, "Current Affairs", "Summits", "medium", 
        "Which country hosted the G20 Summit in the year 2023?", 
        ["India", "Indonesia", "Brazil", "South Africa"], 1)
]

questions_comp = [
    create_question("q-comp-71", 71, "MS Office", "Excel Functions", "medium", 
        "What will be the output of the function '=OR(A1>50, B1<10)' in MS-Excel 2010?", 
        ["TRUE if either A1 is greater than 50 or B1 is less than 10", "TRUE only if both conditions are met", "FALSE if A1 is 60 and B1 is 5", "An error message"], 1),
    create_question("q-comp-72", 72, "MS Office", "Shortcuts", "easy", 
        "Which keyboard shortcut is used to create a new, blank workbook in MS-Excel?", 
        ["Ctrl + N", "Ctrl + O", "Ctrl + W", "Ctrl + M"], 1),
    create_question("q-comp-73", 73, "Computer Organisation", "Memory", "medium", 
        "Which type of memory is non-volatile and is used to store the computer's startup instructions (BIOS)?", 
        ["ROM", "RAM", "Cache", "Virtual Memory"], 1),
    create_question("q-comp-74", 74, "Computer Organisation", "Hardware", "easy", 
        "Which of the following components is known as the 'brain' of the computer?", 
        ["CPU", "Motherboard", "Hard Drive", "RAM"], 1),
    create_question("q-comp-75", 75, "Computer Software", "Utility Software", "medium", 
        "Disk defragmenter is an example of which type of software?", 
        ["Utility Software", "Application Software", "Operating System", "Firmware"], 1),
    create_question("q-comp-76", 76, "Operating System", "Windows Shortcuts", "easy", 
        "What does the keyboard shortcut 'Windows Key + L' do in Windows 10?", 
        ["Locks the computer", "Opens File Explorer", "Minimizes all windows", "Opens the Run dialog"], 1),
    create_question("q-comp-77", 77, "Computer Software", "Statements", "medium", 
        "Which of the following statements is/are true?\n(i) Open-source software provides access to its source code.\n(ii) Freeware and open-source software are exactly the same thing.", 
        ["Only (i)", "Only (ii)", "Both (i) and (ii)", "Neither (i) nor (ii)"], 1),
    create_question("q-comp-78", 78, "Characteristics of Computers", "Statements", "medium", 
        "Identify whether the given statements are true or false.\na) Computers possess artificial intelligence inherently without programming.\nb) Computers can process millions of instructions per second without fatigue.", 
        ["a) False, b) True", "a) True, b) False", "a) True, b) True", "a) False, b) False"], 1),
    create_question("q-comp-79", 79, "Computer Software", "System Software", "medium", 
        "Which of the following is NOT an operating system?", 
        ["Microsoft Office", "Linux", "macOS", "Windows 11"], 1),
    create_question("q-comp-80", 80, "MS Office", "Excel Formula", "hard", 
        "What will be the output of the following MS-Excel formula?\n= (8 / 2) * (2 + 2) + 3^2", 
        ["25", "17", "13", "34"], 1)
]

all_questions = questions_q + questions_verbal + questions_reasoning + questions_ga + questions_comp

paper = {
    "id": "iisc-aa-platinum",
    "title": "IISc Administrative Assistant - Platinum Guess Paper",
    "durationMinutes": 150,
    "instructions": [
        "This is a Platinum quality guess paper modelled strictly after the 2023 official paper.",
        "Total questions: 80.",
        "Each question carries equal marks."
    ],
    "sections": [
        {
            "id": "quantitative-ability",
            "title": "Quantitative Ability",
            "metadata": {"section": "Quantitative Ability"},
            "questions": questions_q
        },
        {
            "id": "verbal-ability",
            "title": "Verbal Ability",
            "metadata": {"section": "Verbal Ability"},
            "questions": questions_verbal
        },
        {
            "id": "logical-reasoning",
            "title": "Logical & Numerical Reasoning",
            "metadata": {"section": "Logical & Numerical Reasoning"},
            "questions": questions_reasoning
        },
        {
            "id": "general-awareness",
            "title": "General Awareness",
            "metadata": {"section": "General Awareness"},
            "questions": questions_ga
        },
        {
            "id": "computer-applications",
            "title": "Knowledge in Computer Applications",
            "metadata": {"section": "Knowledge in Computer Applications"},
            "questions": questions_comp
        }
    ]
}

with open("papers/iisc-aa-platinum.json", "w") as f:
    json.dump(paper, f, indent=2)
print("Generated papers/iisc-aa-platinum.json with 80 questions.")
